## docker-compose.yml


```yaml
version: '3.8'
services:
web:
build: .
command: python manage.py runserver 0.0.0.0:8000
volumes:
- .:/app
- ./media:/app/media
ports:
- "8000:8000"
environment:
- DEBUG=1
- SECRET_KEY=changeme
depends_on: []
```


---
